export const DUEDATE_OPTIONS = [
  { label: 'Overdue', value: 'OVERDUE' },
  { label: 'Today', value: 'TODAY' },
  { label: 'Tomorrow', value: 'TOMORROW' },
  { label: 'This Week', value: 'THIS_WEEK' },
];

export const TAG_OPTIONS = [
  // Development
  { label: 'UI', value: 'UI' },
  { label: 'UX', value: 'UX' },
  { label: 'Design', value: 'Design' },
  { label: 'Frontend', value: 'Frontend' },
  { label: 'Backend', value: 'Backend' },
  { label: 'Full Stack', value: 'Full Stack' },
  { label: 'Mobile', value: 'Mobile' },
  { label: 'API', value: 'API' },
  { label: 'Database', value: 'Database' },
  { label: 'DevOps', value: 'DevOps' },
  { label: 'Infrastructure', value: 'Infrastructure' },
  { label: 'Cloud', value: 'Cloud' },
  { label: 'Security', value: 'Security' },
  { label: 'Performance', value: 'Performance' },
  { label: 'Testing', value: 'Testing' },
  { label: 'QA', value: 'QA' },
  { label: 'Code Review', value: 'Code Review' },
  { label: 'Refactoring', value: 'Refactoring' },
  { label: 'Bug Fix', value: 'Bug Fix' },
  { label: 'Feature', value: 'Feature' },
  { label: 'Hotfix', value: 'Hotfix' },
  // Project Management
  { label: 'Planning', value: 'Planning' },
  { label: 'Requirements', value: 'Requirements' },
  { label: 'Analysis', value: 'Analysis' },
  { label: 'Design Review', value: 'Design Review' },
  { label: 'Sprint Planning', value: 'Sprint Planning' },
  { label: 'Retrospective', value: 'Retrospective' },
  { label: 'Standup', value: 'Standup' },
  { label: 'Meeting', value: 'Meeting' },
  { label: 'Documentation', value: 'Documentation' },
  { label: 'Timeline', value: 'Timeline' },
  { label: 'Milestone', value: 'Milestone' },
  { label: 'Deadline', value: 'Deadline' },
  { label: 'Priority', value: 'Priority' },
  { label: 'Blocked', value: 'Blocked' },
  { label: 'Dependencies', value: 'Dependencies' },
  // Business & Marketing
  { label: 'Business', value: 'Business' },
  { label: 'Marketing', value: 'Marketing' },
  { label: 'Analytics', value: 'Analytics' },
  { label: 'SEO', value: 'SEO' },
  { label: 'Content', value: 'Content' },
  { label: 'Social Media', value: 'Social Media' },
  { label: 'Email Marketing', value: 'Email Marketing' },
  { label: 'Campaign', value: 'Campaign' },
  { label: 'ROI', value: 'ROI' },
  { label: 'Conversion', value: 'Conversion' },
  { label: 'User Research', value: 'User Research' },
  { label: 'Customer Feedback', value: 'Customer Feedback' },
  { label: 'Sales', value: 'Sales' },
  { label: 'Support', value: 'Support' },
  // Technical Categories
  { label: 'Architecture', value: 'Architecture' },
  { label: 'System Design', value: 'System Design' },
  { label: 'Integration', value: 'Integration' },
  { label: 'Migration', value: 'Migration' },
  { label: 'Deployment', value: 'Deployment' },
  { label: 'Monitoring', value: 'Monitoring' },
  { label: 'Logging', value: 'Logging' },
  { label: 'Backup', value: 'Backup' },
  { label: 'Recovery', value: 'Recovery' },
  { label: 'Scalability', value: 'Scalability' },
  { label: 'Optimization', value: 'Optimization' },
  { label: 'Maintenance', value: 'Maintenance' },
  { label: 'Upgrade', value: 'Upgrade' },
  { label: 'Compliance', value: 'Compliance' },
  { label: 'Audit', value: 'Audit' },
  // Team & Collaboration
  { label: 'Team Lead', value: 'Team Lead' },
  { label: 'Mentoring', value: 'Mentoring' },
  { label: 'Onboarding', value: 'Onboarding' },
  { label: 'Training', value: 'Training' },
  { label: 'Knowledge Share', value: 'Knowledge Share' },
  { label: 'Pair Programming', value: 'Pair Programming' },
  { label: 'Collaboration', value: 'Collaboration' },
  { label: 'External', value: 'External' },
  { label: 'Client', value: 'Client' },
  { label: 'Stakeholder', value: 'Stakeholder' },
  // Time & Urgency
  { label: 'Urgent', value: 'Urgent' },
  { label: 'Critical', value: 'Critical' },
  { label: 'High Priority', value: 'High Priority' },
  { label: 'Low Priority', value: 'Low Priority' },
  { label: 'Quick Win', value: 'Quick Win' },
  { label: 'Long Term', value: 'Long Term' },
  { label: 'Research', value: 'Research' },
  { label: 'Investigation', value: 'Investigation' },
  { label: 'Exploration', value: 'Exploration' },
  { label: 'POC', value: 'POC' },
  { label: 'MVP', value: 'MVP' },
  { label: 'Production', value: 'Production' },
  { label: 'Staging', value: 'Staging' },
  { label: 'Development', value: 'Development' },
  { label: 'Review', value: 'Review' },
  // Industry Specific
  { label: 'E-commerce', value: 'E-commerce' },
  { label: 'Healthcare', value: 'Healthcare' },
  { label: 'Finance', value: 'Finance' },
  { label: 'Education', value: 'Education' },
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Real Estate', value: 'Real Estate' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Food', value: 'Food' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Social', value: 'Social' },
  { label: 'Enterprise', value: 'Enterprise' },
  { label: 'SaaS', value: 'SaaS' },
  { label: 'B2B', value: 'B2B' },
  { label: 'B2C', value: 'B2C' },
];
