/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query Lists($boardId: ID!, $filters: TaskFilterInputType) {\n      lists(boardId: $boardId) {\n        nodes {\n          id\n          name\n          position\n          tasks(filters: $filters) {\n            nodes {\n              id\n              title\n              description\n              dueDate\n              tags\n              priority\n              position\n              isCompleted\n              list {\n                id\n                name\n              }\n              assignees {\n                assignedTo {\n                  fullName\n                }\n              }\n              checklists {\n                id\n              }\n              comments {\n                id\n              }\n              createdAt\n              updatedAt\n            }\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    }\n  ": typeof types.ListsDocument,
    "\n    query Task($boardId: ID!, $taskId: ID!) {\n      task(boardId: $boardId, taskId: $taskId) {\n        id\n        title\n        description\n        dueDate\n        priority\n        position\n        isCompleted\n        tags\n        list {\n          id\n          name\n        }\n        checklists {\n          id\n          label\n          isCompleted\n        }\n        assignees {\n          id\n          assignedTo {\n            id\n            fullName\n          }\n        }\n        comments {\n          id\n          text\n          author {\n            id\n            fullName\n          }\n          createdAt\n          updatedAt\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  ": typeof types.TaskDocument,
    "\n    mutation CreateTaskChecklistItem($boardId: ID!, $taskId: ID!, $label: String!) {\n        createTaskChecklistItem(boardId: $boardId, taskId: $taskId, label: $label) {\n            id\n            label\n            isCompleted\n        }\n    }\n": typeof types.CreateTaskChecklistItemDocument,
    "\n    mutation CreateTaskComment($boardId: ID!, $taskId: ID!, $authorId: ID!, $text: String!) {\n        createTaskComment(boardId: $boardId, taskId: $taskId, authorId: $authorId, text: $text) {\n            id\n            text\n            author {\n                fullName\n            }\n        }\n    }\n": typeof types.CreateTaskCommentDocument,
    "\n    mutation UpdateListPosition($boardId: ID!, $listId: ID!, $newPosition: Int!) {\n        updateListPosition(boardId: $boardId, listId: $listId, newPosition: $newPosition) {\n            id\n            name\n            position\n            createdAt\n            updatedAt\n        }\n    }    \n": typeof types.UpdateListPositionDocument,
    "\n    mutation UpdateTaskName($boardId: ID!, $taskId: ID!, $title: String!) {\n        updateTaskName(boardId: $boardId, taskId: $taskId, title: $title) {\n            id\n            title\n        }\n    }\n": typeof types.UpdateTaskNameDocument,
    "\n    mutation UpdateTaskDescription($boardId: ID!, $taskId: ID!, $description: String!) {\n        updateTaskDescription(boardId: $boardId, taskId: $taskId, description: $description) {\n            id\n            description\n        }\n    }\n": typeof types.UpdateTaskDescriptionDocument,
    "\n    mutation UpdateTaskAssignees($boardId: ID!, $taskId: ID!, $assignees: [ID]!) {\n        updateTaskAssignees(boardId: $boardId, taskId: $taskId, assignees: $assignees) {\n            id\n            assignedTo {\n                fullName\n            }\n        }\n    }\n": typeof types.UpdateTaskAssigneesDocument,
    "\n    mutation UpdateTaskDueDate($boardId: ID!, $taskId: ID!, $dueDate: String!) {\n        updateTaskDueDate(boardId: $boardId, taskId: $taskId, dueDate: $dueDate) {\n            id\n            dueDate\n        }\n    }\n": typeof types.UpdateTaskDueDateDocument,
    "\n    mutation UpdateTaskStatus($boardId: ID!, $taskId: ID!, $isCompleted: Boolean!) {\n        updateTaskStatus(boardId: $boardId, taskId: $taskId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n": typeof types.UpdateTaskStatusDocument,
    "\n    mutation UpdateTaskTags($boardId: ID!, $taskId: ID!, $tags: [String]!) {\n        updateTaskTags(boardId: $boardId, taskId: $taskId, tags: $tags) {\n            id\n            tags\n        }\n    }\n": typeof types.UpdateTaskTagsDocument,
    "\n    mutation UpdateTaskPriority($boardId: ID!, $taskId: ID!, $priority: TaskPriorityEnumType!) {\n        updateTaskPriority(boardId: $boardId, taskId: $taskId, priority: $priority) {\n            id\n            priority\n        }\n    }\n": typeof types.UpdateTaskPriorityDocument,
    "\n    mutation UpdateTaskComment($boardId: ID!, $commentId: ID!, $text: String!) {\n        updateTaskComment(boardId: $boardId, commentId: $commentId, text: $text) {\n            id\n            text\n        }\n    }\n": typeof types.UpdateTaskCommentDocument,
    "\n    mutation DeleteTaskComment($boardId: ID!, $commentId: ID!) {\n        deleteTaskComment(boardId: $boardId, commentId: $commentId) {\n            id\n        }\n    }\n": typeof types.DeleteTaskCommentDocument,
    "\n    mutation UpdateTaskPositionInList($boardId: ID!, $taskId: ID!, $newPosition: Int!) {\n        updateTaskPositionInList(boardId: $boardId, taskId: $taskId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                position\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n": typeof types.UpdateTaskPositionInListDocument,
    "\n    mutation UpdateTaskChecklistStatus($boardId: ID!, $checklistItemId: ID!, $isCompleted: Boolean!) {\n        updateTaskChecklistStatus(boardId: $boardId, checklistItemId: $checklistItemId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n": typeof types.UpdateTaskChecklistStatusDocument,
    "\n    mutation ChangeTaskList($boardId: ID!, $taskId: ID!, $newListId: ID!) {\n        changeTaskList(boardId: $boardId, taskId: $taskId, newListId: $newListId) {\n            id\n            list {\n                id\n            }\n        }\n    }\n": typeof types.ChangeTaskListDocument,
    "\n    mutation ChangeTaskListWithPosition($boardId: ID!, $taskId: ID!, $newListId: ID!, $newPosition: Int!) {\n        changeTaskListWithPosition(boardId: $boardId, taskId: $taskId, newListId: $newListId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }    \n": typeof types.ChangeTaskListWithPositionDocument,
    "\n  mutation CreateList($boardId: ID!, $name: String!) {\n    createList(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n": typeof types.CreateListDocument,
    "\n  query ClientMembers($clientId: ID!) {\n    client(id: $clientId) {\n      members {\n        nodes {\n          id\n          fullName\n          role\n        }\n      }\n    }\n  }\n": typeof types.ClientMembersDocument,
    "\n  mutation UpdateBoardMembers($boardId: ID!, $userIds: [ID!]!) {\n    updateBoardMembers(boardId: $boardId, userIds: $userIds) {\n      id\n      invitedByUser {\n        id\n        fullName\n      }\n      user {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateBoardMembersDocument,
    "\n  mutation DeleteList($boardId: ID!, $listId: ID!) {\n    deleteList(boardId: $boardId, listId: $listId) {\n      id\n      name \n      position\n    }\n  }\n": typeof types.DeleteListDocument,
    "\n  mutation UpdateListName($boardId: ID!, $listId: ID!, $name: String!) {\n    updateListName(boardId: $boardId, listId: $listId, name: $name) {\n      id\n      name\n    }\n  }\n": typeof types.UpdateListNameDocument,
    "\n  mutation CreateTask($boardId: ID!, $listId: ID!, $title: String!) {\n    createTask(boardId: $boardId, listId: $listId, title: $title) {\n      id\n      title\n    }\n  }\n": typeof types.CreateTaskDocument,
    "\n  query BoardMembers($boardId: ID!) {\n    board(id: $boardId) {\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n    }\n  }\n": typeof types.BoardMembersDocument,
    "\n    mutation CloseBoard($boardId: ID!) {\n        closeBoard(boardId: $boardId) {\n            id\n            name\n        }\n    }\n": typeof types.CloseBoardDocument,
    "\n    query BoardInformation($boardId: ID!) {\n        board(id: $boardId) {\n            id\n            name\n            description\n            status\n        }\n    }\n": typeof types.BoardInformationDocument,
    "\n    mutation UpdateBoardInformation($boardId: ID!, $name: String!, $description: String!) {\n        updateBoardInformation(boardId: $boardId, name: $name, description: $description) {\n            id\n            name\n            description\n        }\n    }\n": typeof types.UpdateBoardInformationDocument,
    "\n  query BoardDetails($boardId: ID!) {\n    board(id: $boardId) {\n      id\n      name\n      status\n      description\n      client {\n        id\n        name\n      }\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n      clientAdmins {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.BoardDetailsDocument,
    "\n  query GetSuperAdmins {\n    superAdmins {\n      id\n      fullName\n    }\n  }\n": typeof types.GetSuperAdminsDocument,
    "\n  mutation UpdateBoardName($boardId: ID!, $name: String!) {\n    updateBoardName(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n": typeof types.UpdateBoardNameDocument,
    "\n  mutation CreateBoard($clientId: ID!, $name: String!) {\n    createBoard(clientId: $clientId, name: $name) {\n      id\n      name\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateBoardDocument,
    "\n  query Boards($cursor: ID, $limit: Int, $filters: BoardFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    boards(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        client {\n          name\n        }\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  }\n": typeof types.BoardsDocument,
    "\n  mutation CreateClientAdminUser($email: String!, $fullName: String!, $clientId: String!) {\n    createClientAdminUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n": typeof types.CreateClientAdminUserDocument,
    "\n  mutation CreateMemberUser($email: String!, $fullName: String!, $clientId: String!) {\n    createMemberUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n": typeof types.CreateMemberUserDocument,
    "\n  mutation UpdateClientInformation($clientId: ID!, $name: String!, $description: String!, $status: ClientStatusEnumType!) {\n    updateClientInformation(clientId: $clientId, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateClientInformationDocument,
    "\n  query Client($clientId: ID!) {\n    client(id: $clientId) {\n      id\n      name\n      description\n      status\n      members {\n        nodes {\n          id\n          fullName\n          email\n          role\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      boards {\n        nodes {\n          id\n          name\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.ClientDocument,
    "\n  mutation CreateClientByAdmin($name: String!, $description: String!) {\n    createClientByAdmin(name: $name, description: $description) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateClientByAdminDocument,
    "\n  query Clients($cursor: ID, $limit: Int, $filters: ClientFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    clients(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        description\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        hasNextPage\n        totalCount\n      }\n    }\n  }\n": typeof types.ClientsDocument,
    "\n  query DashboardQuery {\n    dashboard {\n      boardCount\n      memberCount\n      clientCount\n      taskCount\n      completedTaskCount\n      pendingTaskCount\n      immediatePriorityTaskCount\n      highPriorityTaskCount\n    }\n  }\n": typeof types.DashboardQueryDocument,
    "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      token\n      user {\n        id\n        fullName\n        role\n        email\n        clientId\n        status\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation UpdateUserStatus($updateUserStatusId: ID!, $status: UserStatusEnumType!) {\n    updateUserStatus(id: $updateUserStatusId, status: $status) {\n      id\n      fullName\n      status\n    }\n  }\n": typeof types.UpdateUserStatusDocument,
    "\n  query UserInformation($userId: ID!) {\n    user(id: $userId) {\n      id\n      fullName\n      email\n      role\n      status\n      client {\n        id\n        name\n        boards {\n          nodes {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      hasAccessTo {\n        nodes {\n          board {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UserInformationDocument,
    "\n  query Members($cursor: ID, $limit: Int, $filters: UserFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    users(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        fullName\n        email\n        role\n        status\n        client {\n          name\n        }\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  } \n": typeof types.MembersDocument,
    "\n  mutation ResetPassword($email: String!, $oldPassword: String!, $newPassword: String!) {\n    resetPassword(email: $email, oldPassword: $oldPassword, newPassword: $newPassword) {\n      status\n      message\n    }\n  }\n": typeof types.ResetPasswordDocument,
};
const documents: Documents = {
    "\n    query Lists($boardId: ID!, $filters: TaskFilterInputType) {\n      lists(boardId: $boardId) {\n        nodes {\n          id\n          name\n          position\n          tasks(filters: $filters) {\n            nodes {\n              id\n              title\n              description\n              dueDate\n              tags\n              priority\n              position\n              isCompleted\n              list {\n                id\n                name\n              }\n              assignees {\n                assignedTo {\n                  fullName\n                }\n              }\n              checklists {\n                id\n              }\n              comments {\n                id\n              }\n              createdAt\n              updatedAt\n            }\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    }\n  ": types.ListsDocument,
    "\n    query Task($boardId: ID!, $taskId: ID!) {\n      task(boardId: $boardId, taskId: $taskId) {\n        id\n        title\n        description\n        dueDate\n        priority\n        position\n        isCompleted\n        tags\n        list {\n          id\n          name\n        }\n        checklists {\n          id\n          label\n          isCompleted\n        }\n        assignees {\n          id\n          assignedTo {\n            id\n            fullName\n          }\n        }\n        comments {\n          id\n          text\n          author {\n            id\n            fullName\n          }\n          createdAt\n          updatedAt\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  ": types.TaskDocument,
    "\n    mutation CreateTaskChecklistItem($boardId: ID!, $taskId: ID!, $label: String!) {\n        createTaskChecklistItem(boardId: $boardId, taskId: $taskId, label: $label) {\n            id\n            label\n            isCompleted\n        }\n    }\n": types.CreateTaskChecklistItemDocument,
    "\n    mutation CreateTaskComment($boardId: ID!, $taskId: ID!, $authorId: ID!, $text: String!) {\n        createTaskComment(boardId: $boardId, taskId: $taskId, authorId: $authorId, text: $text) {\n            id\n            text\n            author {\n                fullName\n            }\n        }\n    }\n": types.CreateTaskCommentDocument,
    "\n    mutation UpdateListPosition($boardId: ID!, $listId: ID!, $newPosition: Int!) {\n        updateListPosition(boardId: $boardId, listId: $listId, newPosition: $newPosition) {\n            id\n            name\n            position\n            createdAt\n            updatedAt\n        }\n    }    \n": types.UpdateListPositionDocument,
    "\n    mutation UpdateTaskName($boardId: ID!, $taskId: ID!, $title: String!) {\n        updateTaskName(boardId: $boardId, taskId: $taskId, title: $title) {\n            id\n            title\n        }\n    }\n": types.UpdateTaskNameDocument,
    "\n    mutation UpdateTaskDescription($boardId: ID!, $taskId: ID!, $description: String!) {\n        updateTaskDescription(boardId: $boardId, taskId: $taskId, description: $description) {\n            id\n            description\n        }\n    }\n": types.UpdateTaskDescriptionDocument,
    "\n    mutation UpdateTaskAssignees($boardId: ID!, $taskId: ID!, $assignees: [ID]!) {\n        updateTaskAssignees(boardId: $boardId, taskId: $taskId, assignees: $assignees) {\n            id\n            assignedTo {\n                fullName\n            }\n        }\n    }\n": types.UpdateTaskAssigneesDocument,
    "\n    mutation UpdateTaskDueDate($boardId: ID!, $taskId: ID!, $dueDate: String!) {\n        updateTaskDueDate(boardId: $boardId, taskId: $taskId, dueDate: $dueDate) {\n            id\n            dueDate\n        }\n    }\n": types.UpdateTaskDueDateDocument,
    "\n    mutation UpdateTaskStatus($boardId: ID!, $taskId: ID!, $isCompleted: Boolean!) {\n        updateTaskStatus(boardId: $boardId, taskId: $taskId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n": types.UpdateTaskStatusDocument,
    "\n    mutation UpdateTaskTags($boardId: ID!, $taskId: ID!, $tags: [String]!) {\n        updateTaskTags(boardId: $boardId, taskId: $taskId, tags: $tags) {\n            id\n            tags\n        }\n    }\n": types.UpdateTaskTagsDocument,
    "\n    mutation UpdateTaskPriority($boardId: ID!, $taskId: ID!, $priority: TaskPriorityEnumType!) {\n        updateTaskPriority(boardId: $boardId, taskId: $taskId, priority: $priority) {\n            id\n            priority\n        }\n    }\n": types.UpdateTaskPriorityDocument,
    "\n    mutation UpdateTaskComment($boardId: ID!, $commentId: ID!, $text: String!) {\n        updateTaskComment(boardId: $boardId, commentId: $commentId, text: $text) {\n            id\n            text\n        }\n    }\n": types.UpdateTaskCommentDocument,
    "\n    mutation DeleteTaskComment($boardId: ID!, $commentId: ID!) {\n        deleteTaskComment(boardId: $boardId, commentId: $commentId) {\n            id\n        }\n    }\n": types.DeleteTaskCommentDocument,
    "\n    mutation UpdateTaskPositionInList($boardId: ID!, $taskId: ID!, $newPosition: Int!) {\n        updateTaskPositionInList(boardId: $boardId, taskId: $taskId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                position\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n": types.UpdateTaskPositionInListDocument,
    "\n    mutation UpdateTaskChecklistStatus($boardId: ID!, $checklistItemId: ID!, $isCompleted: Boolean!) {\n        updateTaskChecklistStatus(boardId: $boardId, checklistItemId: $checklistItemId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n": types.UpdateTaskChecklistStatusDocument,
    "\n    mutation ChangeTaskList($boardId: ID!, $taskId: ID!, $newListId: ID!) {\n        changeTaskList(boardId: $boardId, taskId: $taskId, newListId: $newListId) {\n            id\n            list {\n                id\n            }\n        }\n    }\n": types.ChangeTaskListDocument,
    "\n    mutation ChangeTaskListWithPosition($boardId: ID!, $taskId: ID!, $newListId: ID!, $newPosition: Int!) {\n        changeTaskListWithPosition(boardId: $boardId, taskId: $taskId, newListId: $newListId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }    \n": types.ChangeTaskListWithPositionDocument,
    "\n  mutation CreateList($boardId: ID!, $name: String!) {\n    createList(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n": types.CreateListDocument,
    "\n  query ClientMembers($clientId: ID!) {\n    client(id: $clientId) {\n      members {\n        nodes {\n          id\n          fullName\n          role\n        }\n      }\n    }\n  }\n": types.ClientMembersDocument,
    "\n  mutation UpdateBoardMembers($boardId: ID!, $userIds: [ID!]!) {\n    updateBoardMembers(boardId: $boardId, userIds: $userIds) {\n      id\n      invitedByUser {\n        id\n        fullName\n      }\n      user {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateBoardMembersDocument,
    "\n  mutation DeleteList($boardId: ID!, $listId: ID!) {\n    deleteList(boardId: $boardId, listId: $listId) {\n      id\n      name \n      position\n    }\n  }\n": types.DeleteListDocument,
    "\n  mutation UpdateListName($boardId: ID!, $listId: ID!, $name: String!) {\n    updateListName(boardId: $boardId, listId: $listId, name: $name) {\n      id\n      name\n    }\n  }\n": types.UpdateListNameDocument,
    "\n  mutation CreateTask($boardId: ID!, $listId: ID!, $title: String!) {\n    createTask(boardId: $boardId, listId: $listId, title: $title) {\n      id\n      title\n    }\n  }\n": types.CreateTaskDocument,
    "\n  query BoardMembers($boardId: ID!) {\n    board(id: $boardId) {\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n    }\n  }\n": types.BoardMembersDocument,
    "\n    mutation CloseBoard($boardId: ID!) {\n        closeBoard(boardId: $boardId) {\n            id\n            name\n        }\n    }\n": types.CloseBoardDocument,
    "\n    query BoardInformation($boardId: ID!) {\n        board(id: $boardId) {\n            id\n            name\n            description\n            status\n        }\n    }\n": types.BoardInformationDocument,
    "\n    mutation UpdateBoardInformation($boardId: ID!, $name: String!, $description: String!) {\n        updateBoardInformation(boardId: $boardId, name: $name, description: $description) {\n            id\n            name\n            description\n        }\n    }\n": types.UpdateBoardInformationDocument,
    "\n  query BoardDetails($boardId: ID!) {\n    board(id: $boardId) {\n      id\n      name\n      status\n      description\n      client {\n        id\n        name\n      }\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n      clientAdmins {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.BoardDetailsDocument,
    "\n  query GetSuperAdmins {\n    superAdmins {\n      id\n      fullName\n    }\n  }\n": types.GetSuperAdminsDocument,
    "\n  mutation UpdateBoardName($boardId: ID!, $name: String!) {\n    updateBoardName(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n": types.UpdateBoardNameDocument,
    "\n  mutation CreateBoard($clientId: ID!, $name: String!) {\n    createBoard(clientId: $clientId, name: $name) {\n      id\n      name\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateBoardDocument,
    "\n  query Boards($cursor: ID, $limit: Int, $filters: BoardFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    boards(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        client {\n          name\n        }\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  }\n": types.BoardsDocument,
    "\n  mutation CreateClientAdminUser($email: String!, $fullName: String!, $clientId: String!) {\n    createClientAdminUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n": types.CreateClientAdminUserDocument,
    "\n  mutation CreateMemberUser($email: String!, $fullName: String!, $clientId: String!) {\n    createMemberUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n": types.CreateMemberUserDocument,
    "\n  mutation UpdateClientInformation($clientId: ID!, $name: String!, $description: String!, $status: ClientStatusEnumType!) {\n    updateClientInformation(clientId: $clientId, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateClientInformationDocument,
    "\n  query Client($clientId: ID!) {\n    client(id: $clientId) {\n      id\n      name\n      description\n      status\n      members {\n        nodes {\n          id\n          fullName\n          email\n          role\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      boards {\n        nodes {\n          id\n          name\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.ClientDocument,
    "\n  mutation CreateClientByAdmin($name: String!, $description: String!) {\n    createClientByAdmin(name: $name, description: $description) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateClientByAdminDocument,
    "\n  query Clients($cursor: ID, $limit: Int, $filters: ClientFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    clients(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        description\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        hasNextPage\n        totalCount\n      }\n    }\n  }\n": types.ClientsDocument,
    "\n  query DashboardQuery {\n    dashboard {\n      boardCount\n      memberCount\n      clientCount\n      taskCount\n      completedTaskCount\n      pendingTaskCount\n      immediatePriorityTaskCount\n      highPriorityTaskCount\n    }\n  }\n": types.DashboardQueryDocument,
    "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      token\n      user {\n        id\n        fullName\n        role\n        email\n        clientId\n        status\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation UpdateUserStatus($updateUserStatusId: ID!, $status: UserStatusEnumType!) {\n    updateUserStatus(id: $updateUserStatusId, status: $status) {\n      id\n      fullName\n      status\n    }\n  }\n": types.UpdateUserStatusDocument,
    "\n  query UserInformation($userId: ID!) {\n    user(id: $userId) {\n      id\n      fullName\n      email\n      role\n      status\n      client {\n        id\n        name\n        boards {\n          nodes {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      hasAccessTo {\n        nodes {\n          board {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.UserInformationDocument,
    "\n  query Members($cursor: ID, $limit: Int, $filters: UserFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    users(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        fullName\n        email\n        role\n        status\n        client {\n          name\n        }\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  } \n": types.MembersDocument,
    "\n  mutation ResetPassword($email: String!, $oldPassword: String!, $newPassword: String!) {\n    resetPassword(email: $email, oldPassword: $oldPassword, newPassword: $newPassword) {\n      status\n      message\n    }\n  }\n": types.ResetPasswordDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Lists($boardId: ID!, $filters: TaskFilterInputType) {\n      lists(boardId: $boardId) {\n        nodes {\n          id\n          name\n          position\n          tasks(filters: $filters) {\n            nodes {\n              id\n              title\n              description\n              dueDate\n              tags\n              priority\n              position\n              isCompleted\n              list {\n                id\n                name\n              }\n              assignees {\n                assignedTo {\n                  fullName\n                }\n              }\n              checklists {\n                id\n              }\n              comments {\n                id\n              }\n              createdAt\n              updatedAt\n            }\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    }\n  "): (typeof documents)["\n    query Lists($boardId: ID!, $filters: TaskFilterInputType) {\n      lists(boardId: $boardId) {\n        nodes {\n          id\n          name\n          position\n          tasks(filters: $filters) {\n            nodes {\n              id\n              title\n              description\n              dueDate\n              tags\n              priority\n              position\n              isCompleted\n              list {\n                id\n                name\n              }\n              assignees {\n                assignedTo {\n                  fullName\n                }\n              }\n              checklists {\n                id\n              }\n              comments {\n                id\n              }\n              createdAt\n              updatedAt\n            }\n          }\n          createdAt\n          updatedAt\n        }\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Task($boardId: ID!, $taskId: ID!) {\n      task(boardId: $boardId, taskId: $taskId) {\n        id\n        title\n        description\n        dueDate\n        priority\n        position\n        isCompleted\n        tags\n        list {\n          id\n          name\n        }\n        checklists {\n          id\n          label\n          isCompleted\n        }\n        assignees {\n          id\n          assignedTo {\n            id\n            fullName\n          }\n        }\n        comments {\n          id\n          text\n          author {\n            id\n            fullName\n          }\n          createdAt\n          updatedAt\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  "): (typeof documents)["\n    query Task($boardId: ID!, $taskId: ID!) {\n      task(boardId: $boardId, taskId: $taskId) {\n        id\n        title\n        description\n        dueDate\n        priority\n        position\n        isCompleted\n        tags\n        list {\n          id\n          name\n        }\n        checklists {\n          id\n          label\n          isCompleted\n        }\n        assignees {\n          id\n          assignedTo {\n            id\n            fullName\n          }\n        }\n        comments {\n          id\n          text\n          author {\n            id\n            fullName\n          }\n          createdAt\n          updatedAt\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation CreateTaskChecklistItem($boardId: ID!, $taskId: ID!, $label: String!) {\n        createTaskChecklistItem(boardId: $boardId, taskId: $taskId, label: $label) {\n            id\n            label\n            isCompleted\n        }\n    }\n"): (typeof documents)["\n    mutation CreateTaskChecklistItem($boardId: ID!, $taskId: ID!, $label: String!) {\n        createTaskChecklistItem(boardId: $boardId, taskId: $taskId, label: $label) {\n            id\n            label\n            isCompleted\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation CreateTaskComment($boardId: ID!, $taskId: ID!, $authorId: ID!, $text: String!) {\n        createTaskComment(boardId: $boardId, taskId: $taskId, authorId: $authorId, text: $text) {\n            id\n            text\n            author {\n                fullName\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CreateTaskComment($boardId: ID!, $taskId: ID!, $authorId: ID!, $text: String!) {\n        createTaskComment(boardId: $boardId, taskId: $taskId, authorId: $authorId, text: $text) {\n            id\n            text\n            author {\n                fullName\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateListPosition($boardId: ID!, $listId: ID!, $newPosition: Int!) {\n        updateListPosition(boardId: $boardId, listId: $listId, newPosition: $newPosition) {\n            id\n            name\n            position\n            createdAt\n            updatedAt\n        }\n    }    \n"): (typeof documents)["\n    mutation UpdateListPosition($boardId: ID!, $listId: ID!, $newPosition: Int!) {\n        updateListPosition(boardId: $boardId, listId: $listId, newPosition: $newPosition) {\n            id\n            name\n            position\n            createdAt\n            updatedAt\n        }\n    }    \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskName($boardId: ID!, $taskId: ID!, $title: String!) {\n        updateTaskName(boardId: $boardId, taskId: $taskId, title: $title) {\n            id\n            title\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskName($boardId: ID!, $taskId: ID!, $title: String!) {\n        updateTaskName(boardId: $boardId, taskId: $taskId, title: $title) {\n            id\n            title\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskDescription($boardId: ID!, $taskId: ID!, $description: String!) {\n        updateTaskDescription(boardId: $boardId, taskId: $taskId, description: $description) {\n            id\n            description\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskDescription($boardId: ID!, $taskId: ID!, $description: String!) {\n        updateTaskDescription(boardId: $boardId, taskId: $taskId, description: $description) {\n            id\n            description\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskAssignees($boardId: ID!, $taskId: ID!, $assignees: [ID]!) {\n        updateTaskAssignees(boardId: $boardId, taskId: $taskId, assignees: $assignees) {\n            id\n            assignedTo {\n                fullName\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskAssignees($boardId: ID!, $taskId: ID!, $assignees: [ID]!) {\n        updateTaskAssignees(boardId: $boardId, taskId: $taskId, assignees: $assignees) {\n            id\n            assignedTo {\n                fullName\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskDueDate($boardId: ID!, $taskId: ID!, $dueDate: String!) {\n        updateTaskDueDate(boardId: $boardId, taskId: $taskId, dueDate: $dueDate) {\n            id\n            dueDate\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskDueDate($boardId: ID!, $taskId: ID!, $dueDate: String!) {\n        updateTaskDueDate(boardId: $boardId, taskId: $taskId, dueDate: $dueDate) {\n            id\n            dueDate\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskStatus($boardId: ID!, $taskId: ID!, $isCompleted: Boolean!) {\n        updateTaskStatus(boardId: $boardId, taskId: $taskId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskStatus($boardId: ID!, $taskId: ID!, $isCompleted: Boolean!) {\n        updateTaskStatus(boardId: $boardId, taskId: $taskId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskTags($boardId: ID!, $taskId: ID!, $tags: [String]!) {\n        updateTaskTags(boardId: $boardId, taskId: $taskId, tags: $tags) {\n            id\n            tags\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskTags($boardId: ID!, $taskId: ID!, $tags: [String]!) {\n        updateTaskTags(boardId: $boardId, taskId: $taskId, tags: $tags) {\n            id\n            tags\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskPriority($boardId: ID!, $taskId: ID!, $priority: TaskPriorityEnumType!) {\n        updateTaskPriority(boardId: $boardId, taskId: $taskId, priority: $priority) {\n            id\n            priority\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskPriority($boardId: ID!, $taskId: ID!, $priority: TaskPriorityEnumType!) {\n        updateTaskPriority(boardId: $boardId, taskId: $taskId, priority: $priority) {\n            id\n            priority\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskComment($boardId: ID!, $commentId: ID!, $text: String!) {\n        updateTaskComment(boardId: $boardId, commentId: $commentId, text: $text) {\n            id\n            text\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskComment($boardId: ID!, $commentId: ID!, $text: String!) {\n        updateTaskComment(boardId: $boardId, commentId: $commentId, text: $text) {\n            id\n            text\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation DeleteTaskComment($boardId: ID!, $commentId: ID!) {\n        deleteTaskComment(boardId: $boardId, commentId: $commentId) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteTaskComment($boardId: ID!, $commentId: ID!) {\n        deleteTaskComment(boardId: $boardId, commentId: $commentId) {\n            id\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskPositionInList($boardId: ID!, $taskId: ID!, $newPosition: Int!) {\n        updateTaskPositionInList(boardId: $boardId, taskId: $taskId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                position\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskPositionInList($boardId: ID!, $taskId: ID!, $newPosition: Int!) {\n        updateTaskPositionInList(boardId: $boardId, taskId: $taskId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                position\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateTaskChecklistStatus($boardId: ID!, $checklistItemId: ID!, $isCompleted: Boolean!) {\n        updateTaskChecklistStatus(boardId: $boardId, checklistItemId: $checklistItemId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTaskChecklistStatus($boardId: ID!, $checklistItemId: ID!, $isCompleted: Boolean!) {\n        updateTaskChecklistStatus(boardId: $boardId, checklistItemId: $checklistItemId, isCompleted: $isCompleted) {\n            id\n            isCompleted\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation ChangeTaskList($boardId: ID!, $taskId: ID!, $newListId: ID!) {\n        changeTaskList(boardId: $boardId, taskId: $taskId, newListId: $newListId) {\n            id\n            list {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation ChangeTaskList($boardId: ID!, $taskId: ID!, $newListId: ID!) {\n        changeTaskList(boardId: $boardId, taskId: $taskId, newListId: $newListId) {\n            id\n            list {\n                id\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation ChangeTaskListWithPosition($boardId: ID!, $taskId: ID!, $newListId: ID!, $newPosition: Int!) {\n        changeTaskListWithPosition(boardId: $boardId, taskId: $taskId, newListId: $newListId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }    \n"): (typeof documents)["\n    mutation ChangeTaskListWithPosition($boardId: ID!, $taskId: ID!, $newListId: ID!, $newPosition: Int!) {\n        changeTaskListWithPosition(boardId: $boardId, taskId: $taskId, newListId: $newListId, newPosition: $newPosition) {\n            id\n            title\n            dueDate\n            tags\n            priority\n            position\n            isCompleted\n            list {\n                id\n                name\n                tasks {\n                    nodes {\n                        id\n                        title\n                        dueDate\n                        tags\n                        priority\n                        position\n                        isCompleted\n                        list {\n                            id\n                            name\n                        }\n                        assignees {\n                            assignedTo {\n                                fullName\n                            }\n                        }\n                        checklists {\n                            id\n                        }\n                        comments {\n                            id\n                        }\n                        createdAt\n                        updatedAt\n                    }\n                }\n                createdAt\n                updatedAt\n            }\n        }\n    }    \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateList($boardId: ID!, $name: String!) {\n    createList(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateList($boardId: ID!, $name: String!) {\n    createList(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query ClientMembers($clientId: ID!) {\n    client(id: $clientId) {\n      members {\n        nodes {\n          id\n          fullName\n          role\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ClientMembers($clientId: ID!) {\n    client(id: $clientId) {\n      members {\n        nodes {\n          id\n          fullName\n          role\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateBoardMembers($boardId: ID!, $userIds: [ID!]!) {\n    updateBoardMembers(boardId: $boardId, userIds: $userIds) {\n      id\n      invitedByUser {\n        id\n        fullName\n      }\n      user {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateBoardMembers($boardId: ID!, $userIds: [ID!]!) {\n    updateBoardMembers(boardId: $boardId, userIds: $userIds) {\n      id\n      invitedByUser {\n        id\n        fullName\n      }\n      user {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteList($boardId: ID!, $listId: ID!) {\n    deleteList(boardId: $boardId, listId: $listId) {\n      id\n      name \n      position\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteList($boardId: ID!, $listId: ID!) {\n    deleteList(boardId: $boardId, listId: $listId) {\n      id\n      name \n      position\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateListName($boardId: ID!, $listId: ID!, $name: String!) {\n    updateListName(boardId: $boardId, listId: $listId, name: $name) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateListName($boardId: ID!, $listId: ID!, $name: String!) {\n    updateListName(boardId: $boardId, listId: $listId, name: $name) {\n      id\n      name\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateTask($boardId: ID!, $listId: ID!, $title: String!) {\n    createTask(boardId: $boardId, listId: $listId, title: $title) {\n      id\n      title\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTask($boardId: ID!, $listId: ID!, $title: String!) {\n    createTask(boardId: $boardId, listId: $listId, title: $title) {\n      id\n      title\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query BoardMembers($boardId: ID!) {\n    board(id: $boardId) {\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query BoardMembers($boardId: ID!) {\n    board(id: $boardId) {\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation CloseBoard($boardId: ID!) {\n        closeBoard(boardId: $boardId) {\n            id\n            name\n        }\n    }\n"): (typeof documents)["\n    mutation CloseBoard($boardId: ID!) {\n        closeBoard(boardId: $boardId) {\n            id\n            name\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query BoardInformation($boardId: ID!) {\n        board(id: $boardId) {\n            id\n            name\n            description\n            status\n        }\n    }\n"): (typeof documents)["\n    query BoardInformation($boardId: ID!) {\n        board(id: $boardId) {\n            id\n            name\n            description\n            status\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    mutation UpdateBoardInformation($boardId: ID!, $name: String!, $description: String!) {\n        updateBoardInformation(boardId: $boardId, name: $name, description: $description) {\n            id\n            name\n            description\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateBoardInformation($boardId: ID!, $name: String!, $description: String!) {\n        updateBoardInformation(boardId: $boardId, name: $name, description: $description) {\n            id\n            name\n            description\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query BoardDetails($boardId: ID!) {\n    board(id: $boardId) {\n      id\n      name\n      status\n      description\n      client {\n        id\n        name\n      }\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n      clientAdmins {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query BoardDetails($boardId: ID!) {\n    board(id: $boardId) {\n      id\n      name\n      status\n      description\n      client {\n        id\n        name\n      }\n      boardMembers {\n        user {\n          id\n          fullName\n        }\n      }\n      clientAdmins {\n        id\n        fullName\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetSuperAdmins {\n    superAdmins {\n      id\n      fullName\n    }\n  }\n"): (typeof documents)["\n  query GetSuperAdmins {\n    superAdmins {\n      id\n      fullName\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateBoardName($boardId: ID!, $name: String!) {\n    updateBoardName(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateBoardName($boardId: ID!, $name: String!) {\n    updateBoardName(boardId: $boardId, name: $name) {\n      id\n      name\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateBoard($clientId: ID!, $name: String!) {\n    createBoard(clientId: $clientId, name: $name) {\n      id\n      name\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateBoard($clientId: ID!, $name: String!) {\n    createBoard(clientId: $clientId, name: $name) {\n      id\n      name\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Boards($cursor: ID, $limit: Int, $filters: BoardFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    boards(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        client {\n          name\n        }\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query Boards($cursor: ID, $limit: Int, $filters: BoardFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    boards(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        client {\n          name\n        }\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateClientAdminUser($email: String!, $fullName: String!, $clientId: String!) {\n    createClientAdminUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation CreateClientAdminUser($email: String!, $fullName: String!, $clientId: String!) {\n    createClientAdminUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateMemberUser($email: String!, $fullName: String!, $clientId: String!) {\n    createMemberUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation CreateMemberUser($email: String!, $fullName: String!, $clientId: String!) {\n    createMemberUser(email: $email, fullName: $fullName, clientId: $clientId) {\n      id\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateClientInformation($clientId: ID!, $name: String!, $description: String!, $status: ClientStatusEnumType!) {\n    updateClientInformation(clientId: $clientId, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateClientInformation($clientId: ID!, $name: String!, $description: String!, $status: ClientStatusEnumType!) {\n    updateClientInformation(clientId: $clientId, name: $name, description: $description, status: $status) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Client($clientId: ID!) {\n    client(id: $clientId) {\n      id\n      name\n      description\n      status\n      members {\n        nodes {\n          id\n          fullName\n          email\n          role\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      boards {\n        nodes {\n          id\n          name\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query Client($clientId: ID!) {\n    client(id: $clientId) {\n      id\n      name\n      description\n      status\n      members {\n        nodes {\n          id\n          fullName\n          email\n          role\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      boards {\n        nodes {\n          id\n          name\n          status\n          createdAt\n          updatedAt\n        }\n        pageInfo {\n          cursor\n          totalCount\n          hasNextPage\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateClientByAdmin($name: String!, $description: String!) {\n    createClientByAdmin(name: $name, description: $description) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateClientByAdmin($name: String!, $description: String!) {\n    createClientByAdmin(name: $name, description: $description) {\n      id\n      name\n      description\n      status\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Clients($cursor: ID, $limit: Int, $filters: ClientFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    clients(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        description\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        hasNextPage\n        totalCount\n      }\n    }\n  }\n"): (typeof documents)["\n  query Clients($cursor: ID, $limit: Int, $filters: ClientFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    clients(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        name\n        description\n        status\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        hasNextPage\n        totalCount\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query DashboardQuery {\n    dashboard {\n      boardCount\n      memberCount\n      clientCount\n      taskCount\n      completedTaskCount\n      pendingTaskCount\n      immediatePriorityTaskCount\n      highPriorityTaskCount\n    }\n  }\n"): (typeof documents)["\n  query DashboardQuery {\n    dashboard {\n      boardCount\n      memberCount\n      clientCount\n      taskCount\n      completedTaskCount\n      pendingTaskCount\n      immediatePriorityTaskCount\n      highPriorityTaskCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      token\n      user {\n        id\n        fullName\n        role\n        email\n        clientId\n        status\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Login($email: String!, $password: String!) {\n    login(email: $email, password: $password) {\n      token\n      user {\n        id\n        fullName\n        role\n        email\n        clientId\n        status\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateUserStatus($updateUserStatusId: ID!, $status: UserStatusEnumType!) {\n    updateUserStatus(id: $updateUserStatusId, status: $status) {\n      id\n      fullName\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateUserStatus($updateUserStatusId: ID!, $status: UserStatusEnumType!) {\n    updateUserStatus(id: $updateUserStatusId, status: $status) {\n      id\n      fullName\n      status\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query UserInformation($userId: ID!) {\n    user(id: $userId) {\n      id\n      fullName\n      email\n      role\n      status\n      client {\n        id\n        name\n        boards {\n          nodes {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      hasAccessTo {\n        nodes {\n          board {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query UserInformation($userId: ID!) {\n    user(id: $userId) {\n      id\n      fullName\n      email\n      role\n      status\n      client {\n        id\n        name\n        boards {\n          nodes {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      hasAccessTo {\n        nodes {\n          board {\n            id\n            name\n            status\n            createdAt\n            updatedAt\n          }\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Members($cursor: ID, $limit: Int, $filters: UserFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    users(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        fullName\n        email\n        role\n        status\n        client {\n          name\n        }\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  } \n"): (typeof documents)["\n  query Members($cursor: ID, $limit: Int, $filters: UserFilterInputType, $sortBy: String, $sortType: SortTypeEnumType) {\n    users(cursor: $cursor, limit: $limit, filters: $filters, sortBy: $sortBy, sortType: $sortType) {\n      nodes {\n        id\n        fullName\n        email\n        role\n        status\n        client {\n          name\n        }\n        createdAt\n        updatedAt\n      }\n      pageInfo {\n        cursor\n        totalCount\n        hasNextPage\n      }\n    }\n  } \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ResetPassword($email: String!, $oldPassword: String!, $newPassword: String!) {\n    resetPassword(email: $email, oldPassword: $oldPassword, newPassword: $newPassword) {\n      status\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ResetPassword($email: String!, $oldPassword: String!, $newPassword: String!) {\n    resetPassword(email: $email, oldPassword: $oldPassword, newPassword: $newPassword) {\n      status\n      message\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;